name: checkout
on:
  push:
  pull_request_target:
  pull_request:
  workflow_dispatch:

jobs:
  checking_out_no_ref:
    name: no_ref
    runs-on: ubuntu-latest
    steps:
      - name: Checkout no ref action
        uses: actions/checkout@v4
      - name: run
        run: ls * && cat *

  checking_out_ref:
    name: ref
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with ref 
        uses: actions/checkout@v4
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - name: run
        run: ls * && cat *
      

  
