name: secret_presence

on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
  check_secret:
    name: Check secret presence
    runs-on: ubuntu-latest
    steps:
    - run: if [[ -z "$EZ" ]]; then exit 55; else echo "secret exists"; fi
    env:
       EZ: ${{ secrets.EZ }}
