name: reference a github variable
on:
  workflow_dispatch:
  
  
jobs:
  check_secret:
    name: Check secret presence
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo " this is a secret: ${{ secrets.VARIABLE }}" | base64
       echo "this is a variable: ${{ env.VARIABLE }} OR $VARIABLE" | base64
    env:
       VARIABLE: ${{ secrets.VARIABLE }}

    
