name: reference a github variable
on:
  workflow_dispatch:
  
  
jobs:
  check_secret:
    name: Check secret presence
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo " this is a secret1: ${{ secrets.ORGSEC1 }}" | base64
       echo "this is aN ENV variable2: ${{ env.VARIABLE1 }} " | base64
       echo "this is a VAR variable3: ${{ vars.VARIABLE2 }} " | base64
    env:
       ORGSEC1: ${{ secrets.ORGSEC1 }}
       VARIABLE1: ${{ secrets.VARIABLE1 }}
       VARIABLE2: ${{ vars.VARIABLE2 }}

    
