name: Internal PR Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  example-job:
    if: github.event.pull_request.head.repo.full_name == ''
    runs-on: ubuntu-latest
    steps:
    - name: Run steps for internal PRs
      run: |
        echo "${{ github.event.pull_request.head.repo.full_name }}" 
        echo "${{ github.repository }}   ONESTEP"

  example-job2:
   # if: (github.event_name == "workflow_dispatch")
    runs-on: ubuntu-latest
    steps:
    - name: Run steps for internal PRs
      run: |
        echo "${{ github.event.pull_request.head.repo.full_name }}" 
        echo "${{ github.repository }}   TWOSTEP"

  example-job3:
    if: 1 == 2 || 1==1
    runs-on: ubuntu-latest
    steps:
    - name: Run steps for internal PRs
      run: |
        echo "${{ github.event.pull_request.head.repo.full_name }}" 
        echo "${{ github.repository }} ${{ github.event_name }}  threestep"

  example-job4:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - name: Run steps for internal PRs
      run: |
        echo "${{ github.event.pull_request.head.repo.full_name }}" 
        echo "${{ github.repository }} ${{ github.event_name }}  4step"
