name: Internal PR Workflow

on:
  workflow_dispatch:

jobs:
  example-job:
    #if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - name: Run steps for internal PRs
      run: echo "${{ github.event.pull_request.head.repo.full_name }}" && echo "${{ github.repository }}
