name: VAULT - HASHICORP
on:
 push:
 workflow_dispatch:

jobs:
  get-vault-secret:
    runs-on: ubuntu-latest

    steps:


    - name: Install Vault CLI
      run: |

        wget https://releases.hashicorp.com/vault/1.15.2/vault_1.15.2_linux_386.zip
        unzip vault_1.15.2_linux_386.zip && sudo mv vault /usr/local/bin/
        
        vault --version
        export VAULT_ADDR=https://50dc-94-71-4-124.ngrok-free.app
        export VAULT_SKIP_VERIFY=1 
        vault login token=${{ secrets.VAULT_TOKEN }}

        SECRET_VALUE=$(vault kv get -field=sec kv/ss)
        echo "$SECRET_VALUE" | base64
